name: Jest Tests

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          ignore-flow: flowname.json
          ignore-rule: rule-bp-node-001
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
